version: '3.6' # specify docker-compose version

# Define the services/containers to be run
services:
  meanapp: # name of the first service
    build: mean-stack # specify the directory of the Dockerfile
    #hostname: localhost 
    ports:
      - "4200:4200" 
      - "4000:4000" 
    environment:
      - NODE_ENV=dev
    links:
      - database

  database: # name of the second service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
